steps:
  # Checkout the source code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--branch', 'master', 'https://github.com/Simrankhott/cloudbuild.git', 'new']

  # Build the application using Maven
  - name: 'maven:3-jdk-11'
    entrypoint: 'mvn'
    args: ['clean', 'package']
