steps:
  # Checkout the source code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--branch', 'master', 'https://github.com/Simrankhott/cloudbuild.git', '.']

  # Build the application using Maven
  - name: 'maven:3-jdk-11'
    entrypoint: 'mvn'
    args: ['clean', 'package']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/myimage:${COMMIT_SHA}'
      - '.'
  
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/myimage:${COMMIT_SHA}'
  
  # Deploy the Docker image to Google Kubernetes Engine
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/mydeployment'
      - 'mycontainer=gcr.io/${PROJECT_ID}/myimage:${COMMIT_SHA}'
